# Generated by Django 4.0.4 on 2022-05-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deaths', models.IntegerField(default=0)),
                ('boss_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='death_counter.boss')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='death_counter.game')),
            ],
        ),
        migrations.AddField(
            model_name='boss',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='death_counter.game'),
        ),
    ]
