# Generated by Django 4.0.4 on 2022-05-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deaths',
            new_name='Death',
        ),
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name_plural': 'Bosses'},
        ),
    ]
