# Generated by Django 4.0.4 on 2022-05-23 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('death_counter', '0002_rename_deaths_death_alter_boss_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='death',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
